export const icons = {
    "right":[
        {
            "name":"步兵",
            "src":"./icon/步兵/步兵.png",
            "size":{
                w:20,h:20
            },
            "list":[
                {
                    name:"机枪兵",
                    src:"./icon/步兵/机枪兵.png"
                },
                {
                    name:"精确射手",
                    src:"./icon/步兵/精确射手.png"
                },
                {
                    name:"轻型反坦克兵",
                    src:"./icon/步兵/轻型反坦克兵.png"
                },
                {
                    name:"重型反坦克兵",
                    src:"./icon/步兵/重型反坦克兵.png"
                },
            ]
        },
        {
            "name":"载具",
            "src":"./icon/载具/载具.png",
            "size":{
                w:20,h:20
            },
            "list":[
                {
                    name:"轻型载具",
                    src:"./icon/载具/轻型载具.png"
                },
                {
                    name:"轻型反装甲载具",
                    src:"./icon/载具/轻型反装甲载具.png"
                },
                {
                    name:"运输载具",
                    src:"./icon/载具/运输载具.png"
                },
                {
                    name:"卡车",
                    src:"./icon/载具/卡车.png"
                },
                {
                    name:"补给卡车",
                    src:"./icon/载具/补给卡车.png"
                },
                {
                    name:"摩托车",
                    src:"./icon/载具/摩托车.png"
                },
            ]
        },

    ]
}
